services:
  - type: web
    name: sudeeep-portfolio
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: DATABASE_URL
        sync: false

